In [47]:
import numpy as np
import time

# Why Numpy over loops?

In [48]:
arr1= np.random.random(10000000)*100
arr2= np.random.random(10000000)*100
start_time= time.time()
count=0;

for i in range(len(arr1)): # Iterate over indices
    count+=arr1[i]*arr2[i] # Use 'i' as index
end_time=time.time()

print("Time taken is: ", end_time-start_time)


Time taken is:  6.09203314781189


In [49]:
arr1= np.random.random(10000000)*100
arr2= np.random.random(10000000)*100
start_time= time.time()
arr3=np.dot(arr1, arr2)
end_time=time.time()

print("Time taken is: ", end_time-start_time)

Time taken is:  0.012138843536376953


From these cell blocks we got to know the loops in python are slower, as compared to numpy, because these libraries are written in cpp

# Q1. Create 2 Numpy array

In [50]:
array1=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 100]])
array2=np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

print("Array 1 is:\n", array1, "\n")
print("Array 1 is:\n", array2, "\n")


Array 1 is:
 [[  1   2   3]
 [  4   5   6]
 [  7   8 100]] 

Array 1 is:
 [[11 12 13]
 [14 15 16]
 [17 18 19]] 



In [51]:
print("Sum of Array is:", array1.shape)
print("Dimension of Array is:", array1.ndim)

Sum of Array is: (3, 3)
Dimension of Array is: 2


# Q2. Sum of 2 matrix

In [52]:
array3 = array1 + array2
array3

array([[ 12,  14,  16],
       [ 18,  20,  22],
       [ 24,  26, 119]])

# Q2. Difference of 2 matrix

In [53]:
array3=array2-array1
array3

array([[ 10,  10,  10],
       [ 10,  10,  10],
       [ 10,  10, -81]])

# Q3. Product of Matrix

In [54]:
# print(array2*array1)
print(array1@array2)
print(np.matmul(array1, array2))
# Both methods works same

[[  90   96  102]
 [ 216  231  246]
 [1889 2004 2119]]
[[  90   96  102]
 [ 216  231  246]
 [1889 2004 2119]]


# Q4. Transpose of Matrix

In [55]:
array3=array2.T
array3

array([[11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])

# Q5. Find the Determinant of Matrix

In [56]:
print(np.linalg.det(array1))

-273.0


# Q6. Find the Inverse of Matrix

In [57]:
print(np.linalg.inv(array1))

[[-1.65567766  0.64468864  0.01098901]
 [ 1.31135531 -0.28937729 -0.02197802]
 [ 0.01098901 -0.02197802  0.01098901]]


# Q6. Find the Trace of Matrix

In [58]:
print(np.linalg.trace(array1))

106


# Q7. Find the Rank of Matrix

In [59]:
print(np.linalg.matrix_rank(array1))

3


# Q8. Find the Eigen value and Eigen vector of Matrix

In [60]:
print(np.linalg.eig(array1))

EigResult(eigenvalues=array([100.73143433,  -0.47210138,   5.74066705]), eigenvectors=array([[-0.03128462, -0.81256792, -0.32993052],
       [-0.063824  ,  0.5827771 , -0.93824424],
       [-0.99747069,  0.01020939,  0.10413258]]))
