## NUMPY on real world dataset

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [18]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([ # It a 2D Array
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print('=='*5, 'Zomato sales Analysis', '=='*5)
print('sales data Shape is: ', sales_data.shape)
print('\n Original data is:\n')
#print(sales_data[:5:])
print(sales_data[:, 1:]) # see the shape its 5x5 so there are 5 rows and 5 columns

========== Zomato sales Analysis ==========
sales data Shape is:  (5, 5)

 Original data is:

[[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


## Total sales per year

In [38]:
print('The Total sales for Paradise Biryani 21-24 is: ', sum(sales_data[0, 1:]))
print('The Total sales on Zomato 23 is: ', np.sum(sales_data[ : , 1:], axis=0))

# if wanted to find the sum of all rows at once, use axis as show above
# same as the previous one, axis=0, denotes columns and axis=1 denotes rows

The Total sales for Paradise Biryani 21-24 is:  800000
The Total sales on Zomato 23 is:  [ 810000  945000 1085000 1240000]


In [34]:
# Print sing loops slaes for each year

for i in range (1,5,1):
  print('The Total sales on Zomato',20+i, 'is: ', sum(sales_data[ : , i]))

The Total sales on Zomato 21 is:  810000
The Total sales on Zomato 22 is:  945000
The Total sales on Zomato 23 is:  1085000
The Total sales on Zomato 24 is:  1240000


In [43]:
# maximum sales per resturant
max_sale= np.sum(np.max(sales_data[:, 1: ], axis=0))
print(max_sale)
print('\n')
min_sale= np.sum(np.min(sales_data[:, 1: ], axis=0))
print(min_sale)

990000


610000


In [52]:
# Average sales per resuturat
avg_sale= np.mean(sales_data[:, 1:], axis=1)# as row wise
print(avg_sale)
print('Avg is: ', avg_sale)


[200000. 152500. 247500. 225000. 195000.]
Avg is:  [200000. 152500. 247500. 225000. 195000.]


In [51]:
# cumulative sales
cumsum=np.cumsum(sales_data[:, 1:], axis=1)
print(cumsum)

[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [53]:
vector=np.array([1, 2, 3, 4])
vector2=np.array([8, 7, 6, 5])

print('Vector Addition: ', vector+vector2)
print('Vector Multiplication: ', vector*vector2)
print('Vector Dont product: ', np.dot(vector, vector2))


Vector Addition:  [9 9 9 9]
Vector Multiplication:  [ 8 14 18 20]
Vector Dont product:  60


In [54]:
 # vectorized Operations
resturent_types=np.array(['burger', 'pizza','coffee', 'food'])

vectorized_upper=np.vectorize(str.upper)
print(vectorized_upper(resturent_types))
 # vectorized Operations are perfored to each element one by one
 # What so ever is the opertion


['BURGER' 'PIZZA' 'COFFEE' 'FOOD']


In [56]:
# broadcast
monthly_avg= sales_data[:, 1:]/12
print(monthly_avg)

# this is the unique feature of Numpy, each element is divided by 12,
# so if we are doing operations with sacler here (2) so we can directly apply the division

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
