In [2]:
import numpy as np

In [6]:
array1=np.array([[1, 2, 3], [4, 5, 6]])
array2=np.random.rand(3, 3)
array3=np.ones((4, 4))

In [8]:
np.save('array1.npy', array1)
np.save('array2.npy', array2)
np.save('array3.npy', array3)

In [11]:
load_array1=np.load('array1.npy')
print(load_array1)
print('\n')
load_array1=np.load('array2.npy')
print(load_array1)
print('\n')
load_array1=np.load('array3.npy')
print(load_array1)

[[1 2 3]
 [4 5 6]]


[[0.54453376 0.5676406  0.66644952]
 [0.8608594  0.23803339 0.550965  ]
 [0.00331405 0.4730242  0.16742763]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
