This is Numpy- Practise- From- chai and code-
https://www.youtube.com/watch?v=x7ULDYs4X84

In [2]:
import numpy as np

Creation of 1D and 2D array

In [11]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array is: ", arr_1d)

arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("2D Array is: ", arr_2d)

1D Array is:  [1 2 3 4 5]
2D Array is:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
print(arr_1d*2)
print('\n')
print(arr_2d*2)

[ 2  4  6  8 10]


[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [17]:
import time
start=time.time()
for i in range (1, 1000000, 1):
  c=1
print('Total time is: ', time.time()-start)

Total time is:  0.16494083404541016


## Creates and Array using inbuilt functions

In [20]:
#  Zeroes
zero=np.zeros((4, 4))
print("Array of Zeros is: \n", zero)

print('\n\n')
ones=np.ones((4, 4))
print("Array of Ones is: \n", ones)
print('\n\n')
full=np.full((4, 4), 7)
print("Array of 7 is: \n", full)
print('\n\n')
random=np.random.random((4, 4))
print("Array of Random Numbers are: \n", random)
print('\n\n')
sequence=np.arange(10, -1, -1)
print("Array of sequence are: \n", sequence)

Array of Zeros is: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



Array of Ones is: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



Array of 7 is: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]



Array of Random Numbers are: 
 [[0.12538192 0.81812107 0.33363956 0.81094762]
 [0.53812079 0.7949211  0.60802643 0.78961283]
 [0.03127098 0.62974996 0.39523463 0.80972891]
 [0.44853818 0.51759472 0.77565433 0.46669661]]



Array of sequence are: 
 [10  9  8  7  6  5  4  3  2  1  0]




*   1-D Array is Vector
*   2-D Array is Matrix
*   More than 2D is considered as Tensors
*   To Process tensors, as their calculation is heavy,
so TPU is requied, i.e Tensor Processing Unit








## Array Properties

In [21]:
arr= np.array([[1, 2, 3], [4, 5, 6]])

#shape
print('shape is: ', arr.shape)
print('Dimension is: ', arr.ndim)
print('Size is: ', arr.size)
print('Data type is: ', arr.dtype)

shape is:  (2, 3)
Dimension is:  2
Size is:  6
Data type is:  int64


In [27]:
arr=np.arange(12)

print('original Array is: ', arr)
print('\n\n')

reshaped= arr.reshape(3, 4)
print('Reshaped is: ', reshaped)
print('\n\n')

falt= reshaped.flatten()
print('Flaterened is: ', falt)
print('\n\n')

ravel= reshaped.ravel()
print('Ravelled is: ', ravel)
print('\n\n')
# flatten creates a copy whereas ravel creates a view

transpose=reshaped.T
print('Transposed is: ', transpose)
print('\n\n')


original Array is:  [ 0  1  2  3  4  5  6  7  8  9 10 11]



Reshaped is:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



Flaterened is:  [ 0  1  2  3  4  5  6  7  8  9 10 11]



Ravelled is:  [ 0  1  2  3  4  5  6  7  8  9 10 11]



Transposed is:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]



