## Numpy Array Operations

Indexing

In [2]:
import numpy as np

In [3]:
arr= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Original Array is: ", arr)
print("Indexed at 2: 7 is: ", arr[2:10]) # last is exclusive
print("Indexed with spaces", arr[1:10:2])
print("Reversed indexing: ", arr[-3]) # last sai 3rd element

Original Array is:  [ 1  2  3  4  5  6  7  8  9 10]
Indexed at 2: 7 is:  [ 3  4  5  6  7  8  9 10]
Indexed with spaces [ 2  4  6  8 10]
Reversed indexing:  8


In [4]:
# on 2D array

arr_2D= np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("Specific Element: ", arr_2D[1, 2])
print("Entire Row: ", arr_2D[0])
print('Entire Colums: ', arr_2D[:, 1])

Specific Element:  6
Entire Row:  [1 2 3]
Entire Colums:  [2 5 8]


## Sorting

In [5]:
arr=np.array([7, 6, 5, 4, 3, 2, 1])
print("Original Array is: ", arr)
print("\n\n")
asec=np.sort(arr)
print("Sorted Array in Asec is: ", np.sort(arr))

print("\n\n")
print("Sorted Array in DESC is: ", asec[::-1])

Original Array is:  [7 6 5 4 3 2 1]



Sorted Array in Asec is:  [1 2 3 4 5 6 7]



Sorted Array in DESC is:  [7 6 5 4 3 2 1]


Sorting of 2 D Array

In [6]:
arr=np.array([[3, 1], [1, 2], [2, 3]])
print("Original Arrays is: \n", arr)
print("\n\n")

print("Column wise sorting: \n", np.sort(arr, axis=0))
print("\n\n")
print("Row wise sorting: \n", np.sort(arr, axis=1))


Original Arrays is: 
 [[3 1]
 [1 2]
 [2 3]]



Column wise sorting: 
 [[1 1]
 [2 2]
 [3 3]]



Row wise sorting: 
 [[1 3]
 [1 2]
 [2 3]]


## Filtering in Numpy

In [17]:
array= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# using range
even_numbers= array[1: 11: 2]
print("Even Numbers with range are: ", even_numbers)

# using Expression or say mask
even_numbers= array[array%2==0]
print("Even Numbers with expressions are: ", even_numbers)

# even the numpy give us the flexiblity to write expression under array indexs
mask = array>=5
print('\n')
print(array[mask])

Even Numbers with range are:  [ 2  4  6  8 10]
Even Numbers with expressions are:  [ 2  4  6  8 10]


[ 5  6  7  8  9 10]


## Fancy Indexing

In [20]:
# Fancy indexing- Instead of passing a indexing, we pass a list of indexs
index= [0, 2, 5, 8]
print(array[index])

# np.where()- This sets a condition
condition= np.where(array>5)
print(condition) # here we can see that the np. where have stored the indexs, where the condition got satisfied
print("The Array with condition is: ", array[condition])

[1 3 6 9]
(array([5, 6, 7, 8, 9]),)
The Array with condition is:  [ 6  7  8  9 10]


In [28]:
condition= np.where(array>5, 'true', 'False')
print(condition)

''' syntax is like
if(array>5){
true
}
else{
false} '''

['False' 'False' 'False' 'False' 'False' 'true' 'true' 'true' 'true'
 'true']


' syntax is like \nif(array>5){\ntrue\n}\nelse{\nfalse} '

## Adding and removing data

In [44]:
## Addition
arr1= np.array([1, 2, 3])
arr2= np.array([4, 5, 6, 7])

# result= arr1+arr2 # so this added (+) array element by elemet, where the size of the array become important
# print(result)

# if there are unequal elements in the array, this will throw an error
# then the question may come how to get the size of an array to check if they are same or not

if arr1.shape==arr2.shape:
  print('Equal')
else:
  print('Not Equal')


if(arr1.shape != arr2.shape):  # if the shape is not equal, just merge the arrays
  result= np.concatenate((arr1, arr2)) # a Tuple is passed
print(result)

Not Equal
[1 2 3 4 5 6 7]


In [54]:
# how to add a single element to the end of the array
# arr1=np.append(arr1, 1)
# print(arr1)
arr1 = np.delete(arr1, 3)
print(arr1)

[1 2 3]


In [58]:
# now the thing is to add into the 2D array or says N- D array
arr1=np.array([[1, 2],
               [3, 4],
               [5, 6]])

# add a row to the existing array- use Vstack
new_row= np.array([9, 10])
answer=np.vstack((arr1, new_row)) # passes as a tuple
print(answer)

print('\n\n Added Columns')
new_col= np.array([[9], [10], [11]]) # give entry as a seprate rows
answer=np.hstack((arr1, new_col)) # passes as a tuple
print(answer)




[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 9 10]]


 Added Columns
[[ 1  2  9]
 [ 3  4 10]
 [ 5  6 11]]
